set -g escape-time 0
set -g base-index 1
set -g renumber-windows on
set -g default-shell /usr/bin/fish

set -g default-terminal "tmux-256color"
set -as terminal-features ",*:RGB"
set -as terminal-overrides ",*:Tc"
set -g focus-events on 

unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

bind r source-file ~/.config/tmux/tmux.conf

set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'

set -g status-position top
set -g status-justify absolute-centre
set -g status-style "fg=color7 bg=default"
set -g status-left " #S "
set -g status-left-style "fg=color5"
set -g status-left-length 96
set -g status-right ""
set -g status-right-length 0

setw -g window-status-current-style "fg=color6 bg=default bold"
setw -g window-status-current-format "#I:#W "
setw -g window-status-style "fg=color3"

bind-key -r f run-shell "tmux new-window $HOME/scripts/tmux-session-handler.sh"
bind-key -r g run-shell "$HOME/scripts/tmux-to-github.sh"
bind-key -r ^ last-window
